### PR TITLE
added jwt

### PR DESCRIPTION
**Pull request by abhay2jn**
### Title
Implement JWT Authentication for Canvas Server

### Description
- **What does this PR do?**
  This PR implements JWT authentication for the Canvas server, enabling secure user sessions.

### Changes Made
- Added JWT authentication middleware.
- Created login and protected routes.
- Updated server configuration to support authentication.
- Implemented error handling for unauthorized access.

### Routes

   - **Ping**: `GET /rest/v1/ping` (should return `pong`)
   - **Login**: `POST /rest/v1/login` with `{ "token": "canvas-server-token" }` (should return an access token)
   - **Protected Route**: `GET /rest/v1/protected` with `Authorization: Bearer <your_access_token>` (should return user data)

### Additional Notes
- Added dependencies: `jsonwebtoken`, `cors`.
- Future improvements may include more robust error handling and user role management.

### CODE REVIEW

**Comment by idncsk** [comment]
Hello, before I start asking who where how, please always work against the dev branch - let me update the ticket accordingly. "dev" hosts the refactored canvas-server runtime-in-the-making
Btw thanks!

**Comment by idncsk** [comment]
Additionally, is that PR message coming from cursor?

**Comment by abhay2jn** [comment]
if u like that changes then i think u should approve my pr

**Comment by idncsk** [comment]
Closing as this was already partly implemented in dev

**Pull request closed without merging**
